name: gemini_genius
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.0
  meta: ^1.3.0
  flutter_bloc: ^8.0.0
  cupertino_icons: ^1.0.2
  dio:
  lottie: ^3.1.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/N.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg_image.jpg
    - assets/loader.json

fonts:
  - family: Roboto  # Name of the font family (Roboto)
    fonts:        # List of font assets
      - asset: assets/Roboto-Medium.ttf  # Path to regular weight font
